# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/assis/OneDrive/Documentos/MEGA/MEGAsync/Curso/Semestre 5/Sistemas Digitais/Praticas_VHDL/Code_Vivado/exemplo_fsm/exemplo_fsm.srcs/constrs_1/new/zybo.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_video_out_0_0/design_1_video_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_video_out_0_0 || ORIG_REF_NAME==design_1_video_out_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pdi_0_0/design_1_pdi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_pdi_0_0 || ORIG_REF_NAME==design_1_pdi_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_video_source_0_0/design_1_video_source_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_video_source_0_0 || ORIG_REF_NAME==design_1_video_source_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rom_0_0/design_1_rom_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rom_0_0 || ORIG_REF_NAME==design_1_rom_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
