# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/assis/OneDrive/Área de Trabalho/files_sd_cpu_vga/ZYBO_Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cpu_0_0/design_1_cpu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_cpu_0_0 || ORIG_REF_NAME==design_1_cpu_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_terminal_vga_0_0/design_1_terminal_vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_terminal_vga_0_0 || ORIG_REF_NAME==design_1_terminal_vga_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cpu_vga_dbg_0_0/design_1_cpu_vga_dbg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_cpu_vga_dbg_0_0 || ORIG_REF_NAME==design_1_cpu_vga_dbg_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ram_0_0/design_1_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ram_0_0 || ORIG_REF_NAME==design_1_ram_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rom_0_0/design_1_rom_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rom_0_0 || ORIG_REF_NAME==design_1_rom_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
